# Generated by Django 2.0.7 on 2018-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='next_semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester I'), (2, 'Semester II'), (3, 'Semester III'), (4, 'Semester IV'), (5, 'Semester V'), (6, 'Semester VI'), (7, 'Semester VII'), (8, 'Semester VIII'), (9, 'Semester IX'), (10, 'Semester X')], null=True),
        ),
    ]
