# Generated by Django 2.0.7 on 2018-08-06 16:26

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0002_auto_20180803_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='core_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'Slot A'), ('B', 'Slot B'), ('C', 'Slot C'), ('D', 'Slot D'), ('E', 'Slot E'), ('F', 'Slot F'), ('G', 'Slot G'), ('H', 'Slot H'), ('P', 'Slot P'), ('Q', 'Slot Q'), ('R', 'Slot R'), ('S', 'Slot S'), ('T', 'Slot T')], max_length=1, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_CGPA',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
    ]
