# Generated by Django 2.0.7 on 2018-08-06 16:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0003_auto_20180806_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
    ]
