# Generated by Django 2.0 on 2018-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0004_auto_20180806_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
