# Generated by Django 2.0 on 2018-08-08 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0005_auto_20180808_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='core_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Slot A'), ('B', 'Slot B'), ('C', 'Slot C'), ('D', 'Slot D'), ('E', 'Slot E'), ('F', 'Slot F'), ('G', 'Slot G'), ('H', 'Slot H'), ('P', 'Slot P'), ('Q', 'Slot Q'), ('R', 'Slot R'), ('S', 'Slot S'), ('T', 'Slot T')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
