# Generated by Django 2.0 on 2018-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0009_auto_20180809_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
