# Generated by Django 2.0 on 2018-08-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0010_auto_20180809_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Slots',
            new_name='Elective',
        ),
        migrations.RenameModel(
            old_name='Course_Departments',
            new_name='Elective_Department',
        ),
        migrations.RenameField(
            model_name='elective_department',
            old_name='course_slot',
            new_name='elective',
        ),
        migrations.RenameField(
            model_name='student_cot_allotment',
            old_name='course_slot',
            new_name='elective',
        ),
        migrations.RenameField(
            model_name='student_elective_allotment',
            old_name='course_slot',
            new_name='elective',
        ),
        migrations.RenameField(
            model_name='student_elective_preference',
            old_name='course_slot',
            new_name='elective',
        ),
    ]
