# Generated by Django 2.0 on 2018-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0012_auto_20180828_0700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elective_seats',
            unique_together={('elective', 'dept')},
        ),
        migrations.AlterUniqueTogether(
            name='student_cot_allotment',
            unique_together={('student', 'elective')},
        ),
    ]
