# Generated by Django 2.0 on 2018-08-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0013_auto_20180829_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elective',
            unique_together={('course', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='student_elective_allotment',
            unique_together={('student', 'elective')},
        ),
        migrations.AlterUniqueTogether(
            name='student_elective_preference',
            unique_together={('student', 'elective')},
        ),
    ]
