# Generated by Django 2.0 on 2018-08-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0015_auto_20180829_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusive_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_courses_course', to='gep_app.Course')),
                ('course_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_courses_exclusive_course', to='gep_app.Course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exclusive_courses',
            unique_together={('course_A', 'course_B')},
        ),
    ]
