# Generated by Django 2.0 on 2018-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0016_auto_20180829_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='past_courses',
            field=models.ManyToManyField(blank=True, null=True, to='gep_app.Course'),
        ),
    ]
