# Generated by Django 2.0 on 2018-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0018_auto_20180830_0807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exclusive_courses',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exclusive_courses',
            name='course_A',
        ),
        migrations.RemoveField(
            model_name='exclusive_courses',
            name='course_B',
        ),
        migrations.AlterField(
            model_name='student',
            name='past_courses',
            field=models.ManyToManyField(blank=True, null=True, to='gep_app.Course'),
        ),
        migrations.DeleteModel(
            name='Exclusive_Courses',
        ),
    ]
