version: '3'

services:
  db:
    image: postgres
    container_name: gep_db
    environment:
      POSTGRES_USER: devika
      POSTGRES_PASSWORD: devika123
      POSTGRES_DB: global_elective_portal
    restart: always
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data

  web:
    build: ./web
    container_name: gep_web
    command: ["bash", "./wait_for_db.sh", "gep_db", "--", "python", "./gep_project/manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - ./web/gep_project:/code/gep_project
    ports:
      - "8000:8000"
    depends_on:
      - db
