"""
Django settings for gep_project project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b&w*7hb&7*l$x#nti7$xv47+*yf-ebzlc429+1emi1jst!5qdj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# DEVELOPMENT
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'gep_app.apps.GepAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
	'django.contrib.messages',
#DEVELOPMENT
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'gep_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gep_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'global_elective_portal',
        'USER': 'devika',
        'PASSWORD': 'devika123',
        'HOST': 'gep_db',
        'PORT': '5432',
    }
}

# SMTP Connection
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'smileydevu@gmail.com'
EMAIL_HOST_PASSWORD = 'iamdev@23'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# User model
AUTH_USER_MODEL = 'gep_app.User'

# Login URL
LOGIN_URL = 'login'

# Login redirect
LOGIN_REDIRECT_URL = 'home'

# Logout redirect
LOGOUT_REDIRECT_URL = 'login'

#Authentication backends
AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
    )

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 5,
        }
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# App configurations
APP_CONFIG = {
	'gep_app' : {
		'ACADEMIC_DATA_SUBMISSION_START_DATE': '2018-09-10T00:00:00',
		'ACADEMIC_DATA_SUBMISSION_END_DATE': '2018-10-20T00:00:00',
		'PREFERENCE_SUBMISSION_START_DATE': '2018-10-10T00:00:00',
		'PREFERENCE_SUBMISSION_END_DATE': '2018-10-10T00:00:00',
		'ALLOTMENT_PUBLICATION_START_DATE': '2018-09-10T00:00:00',
		'ALLOTMENT_PUBLICATION_END_DATE': '2018-09-10T00:00:00',
	}
}
