# Generated by Django 2.0.7 on 2018-07-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='COT_Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('credits', models.IntegerField()),
                ('pre_requisites', models.TextField(blank=True, max_length=500, null=True)),
                ('cot_status', models.BooleanField(default=False)),
                ('cgpa_cutoff', models.IntegerField(default=0)),
                ('mode_of_allotment', models.CharField(blank=True, choices=[('FCFS', 'First Come First Served'), ('CGPA', 'Current CGPA')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elective_Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_rank', models.IntegerField()),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Course_Slots')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=100)),
                ('current_CGPA', models.IntegerField(blank=True, null=True)),
                ('next_semester', models.IntegerField(blank=True, null=True)),
                ('no_of_global_electives', models.IntegerField(blank=True, null=True)),
                ('submission_datetime', models.DateTimeField(blank=True, null=True)),
                ('FA_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gep_app.Faculty')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Core_Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student')),
            ],
        ),
        migrations.AddField(
            model_name='elective_preference',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
        migrations.AddField(
            model_name='course_departments',
            name='course_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Course_Slots'),
        ),
        migrations.AddField(
            model_name='course_departments',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gep_app.Faculty'),
        ),
        migrations.AddField(
            model_name='cot_allotment',
            name='course_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Course_Slots'),
        ),
        migrations.AddField(
            model_name='cot_allotment',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='course_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Course_Slots'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
    ]
