# Generated by Django 2.0.7 on 2018-07-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='course_departments',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='course_slots',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='FA_id',
            new_name='FA',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.AlterField(
            model_name='allotment',
            name='roll_number',
            field=models.ForeignKey(db_column='roll_number', on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
        migrations.AlterField(
            model_name='cot_allotment',
            name='roll_number',
            field=models.ForeignKey(db_column='roll_number', on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
        migrations.AlterField(
            model_name='elective_preference',
            name='roll_number',
            field=models.ForeignKey(db_column='roll_number', on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
        migrations.AlterField(
            model_name='student_core_slots',
            name='roll_number',
            field=models.ForeignKey(db_column='roll_number', on_delete=django.db.models.deletion.CASCADE, to='gep_app.Student'),
        ),
    ]
