# Generated by Django 2.0.7 on 2018-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0002_auto_20180719_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
