# Generated by Django 2.0.7 on 2018-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0004_auto_20180721_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
