# Generated by Django 2.0.7 on 2018-07-31 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0005_auto_20180731_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_slots',
            name='slot',
            field=models.CharField(choices=[('A', 'Slot A'), ('B', 'Slot B'), ('C', 'Slot C'), ('D', 'Slot D'), ('E', 'Slot E'), ('F', 'Slot F'), ('G', 'Slot G'), ('H', 'Slot H'), ('P', 'Slot P'), ('Q', 'Slot Q'), ('R', 'Slot R'), ('S', 'Slot S'), ('T', 'Slot T')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='core_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Slot A'), ('B', 'Slot B'), ('C', 'Slot C'), ('D', 'Slot D'), ('E', 'Slot E'), ('F', 'Slot F'), ('G', 'Slot G'), ('H', 'Slot H'), ('P', 'Slot P'), ('Q', 'Slot Q'), ('R', 'Slot R'), ('S', 'Slot S'), ('T', 'Slot T')], max_length=1), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='next_semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester I'), (2, 'Semester II'), (3, 'Semester III'), (4, 'Semester IV'), (5, 'Semester V'), (6, 'Semester VI'), (7, 'Semester VII'), (8, 'Semester VIII'), (9, 'Semester IX'), (10, 'Semester X')], null=True),
        ),
    ]
