# Generated by Django 2.0.7 on 2018-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0006_auto_20180731_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COT_Allotment',
            new_name='Student_COT_Allotment',
        ),
        migrations.RenameModel(
            old_name='Allotment',
            new_name='Student_Elective_Allotment',
        ),
        migrations.RenameModel(
            old_name='Elective_Preference',
            new_name='Student_Elective_Preference',
        ),
    ]
