# Generated by Django 2.0 on 2018-09-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mutually_Exclusive_Courses',
            new_name='Mutually_Exclusive_Course_Group',
        ),
        migrations.RenameField(
            model_name='mutually_exclusive_course_group',
            old_name='course_group',
            new_name='courses',
        ),
    ]
