# Generated by Django 2.0 on 2018-09-20 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0006_course_allowed_semesters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cgpa_cutoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
