# Generated by Django 2.0 on 2018-10-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0008_course_core_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='core_slots',
        ),
    ]
