# Generated by Django 2.0 on 2018-10-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_app', '0012_student_allowed_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='allowed_semesters',
        ),
    ]
